spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/biblio
        username: biblio
        password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
tracer:
    property: I AM THE DEFAULT

