spring:
    database:
    driverClassName: org.postgresql.Driver
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/biblio
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
tracer:
  property: I AM THE DEFAULT

