spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/biblio
tracer:
  property: I AM THE DEFAULT

